#ifndef ARNE_H
#define ARNE_H 1

{* Arne.h - Vampire SAGA Arne 16-bit audio submod for ACE BASIC *}

CONST ARNE_PAL_CLOCK = 3546895
CONST ARNE_8BIT      = 0
CONST ARNE_16BIT     = 1
CONST ARNE_ONESHOT   = 2
CONST ARNE_STEREO    = 4
CONST ARNE_LOOP16S   = 5
CONST ARNE_PLAY16S   = 7
CONST ARNE_LOOP8     = 0
CONST ARNE_PLAY8     = 2
CONST ARNE_MAX_CH    = 16

DECLARE SUB ArnePlay(SHORTINT ch, LONGINT buf, LONGINT sz, ~
                     SHORTINT per, SHORTINT vl, SHORTINT vr, ~
                     SHORTINT md) EXTERNAL
DECLARE SUB ArneStop(SHORTINT ch) EXTERNAL
DECLARE SUB ArneStart(SHORTINT ch) EXTERNAL
DECLARE SUB ArneVolume(SHORTINT ch, SHORTINT vl, SHORTINT vr) EXTERNAL
DECLARE SUB SHORTINT ArneIsFree(SHORTINT ch) EXTERNAL
DECLARE SUB SHORTINT ArneFindFree EXTERNAL
DECLARE SUB ArneStopAll EXTERNAL
DECLARE SUB SHORTINT ArnePeriod(LONGINT rate) EXTERNAL

#endif
