#ifndef SAGASOUND_H
#define SAGASOUND_H 1

{* SagaSound.h - Vampire SAGA 16-bit audio submod for ACE BASIC *}

CONST SAGASOUND_PAL_CLOCK = 3546895
CONST SAGASOUND_8BIT      = 0
CONST SAGASOUND_16BIT     = 1
CONST SAGASOUND_ONESHOT   = 2
CONST SAGASOUND_STEREO    = 4
CONST SAGASOUND_LOOP16S   = 5
CONST SAGASOUND_PLAY16S   = 7
CONST SAGASOUND_LOOP8     = 0
CONST SAGASOUND_PLAY8     = 2
CONST SAGASOUND_MAX_CH    = 16

DECLARE SUB SagaSoundPlay(SHORTINT ch, LONGINT buf, LONGINT sz, ~
                          SHORTINT per, SHORTINT vl, SHORTINT vr, ~
                          SHORTINT md) EXTERNAL
DECLARE SUB SagaSoundStop(SHORTINT ch) EXTERNAL
DECLARE SUB SagaSoundStart(SHORTINT ch) EXTERNAL
DECLARE SUB SagaSoundVolume(SHORTINT ch, SHORTINT vl, SHORTINT vr) EXTERNAL
DECLARE SUB SHORTINT SagaSoundIsFree(SHORTINT ch) EXTERNAL
DECLARE SUB SHORTINT SagaSoundFindFree EXTERNAL
DECLARE SUB SagaSoundStopAll EXTERNAL
DECLARE SUB SHORTINT SagaSoundPeriod(LONGINT rate) EXTERNAL

#endif
